version: '3.8'
services:
  backend:
    build: ../odk-api
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  frontend:
    build: ../react-work/react-app
    ports:
      - "3000:80"
    depends_on:
      - backend
  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: odkdev
      MYSQL_ROOT_PASSWORD: 7729
    ports:
      - "3307:3306"
    command: --lower_case_table_names=1
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  
volumes:
  mysql-data: